---
title: "Project_Overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Project_Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Description
```{r setup}
library(SouthAfricaDrought)
library(geospaar)
library(sf)
library(rgdal)
library(raster)


#Load farmer data

boundary <- read_sf(dsn = "C:/Users/Emily/Documents/Fall_2020/Geospatial_R/SouthAfricaDrought/data-raw", layer = "SouthAfrica_Boundary")
print(boundary$geometry)

farmers <- read_csv(system.file("extdata/farmer_spatial.csv", package = "geospaar")) %>% distinct(uuid, x, y, date, season, rained, planted)

unique(farmers$date)

#Load worldclim data

#load raster imagery
b <- brick(file.path("C:/Users/Emily/Documents/Fall_2020/Geospatial_R", "noid_image_2020_11_09_14_59_55_2020_11_09_14_59_56.tif"))

b_dec_2016 <- brick(file.path("C:/Users/Emily/Documents/Fall_2020/Geospatial_R", "DEC_image_2020_11_09_15_37_31_2020_11_09_15_37_32.tif"))



plot(b)
plot(b_dec_2016)
```
# Methods

# Data Visualization

# Results
